license: ""

spawn:
  location:
    world: world
    x: -24
    y: 60
    z: -10
    yaw: -179.90935
    pitch: 0.6258706
    worldId: 422980e3-a277-4133-957a-e2000eea67be
    min:
      x: -350
      y: 15
      z: -350
    max:
      x: 350
      y: 256
      z: 350

selector:
  item: "COMPASS"
  name: "<rainbow>Server Selector"
  enchantments:
    - "DURABILITY:10"
  lore:
    - ""
    - "<red>hey"
    - ""
  amount: 1
  slot: 1
hub:
  item: "CLOCK"
  name: "<rainbow>Hub Selector"
  enchantments:
    - "DURABILITY:10"
  lore:
    - ""
    - "<red>hey"
    - ""
  amount: 1
  slot: 2
pvp:
  item: "DIAMOND_SWORD"
  name: "<rainbow>PvP"
  enchantments:
    - "DURABILITY:10"
  lore:
    - ""
    - "<red>hey"
    - ""
  amount: 1
  slot: 3
enderbutt:
  item: "ENDER_PEARL"
  name: "<rainbow>EnderButt"
  enchantments:
    - "DURABILITY:10"
  lore:
    - ""
    - "<red>hey"
    - ""
  amount: 1
  slot: 4
inventory:
  selector:
    title: "<green>inventory"
    size: 54
    items:
      1:
        item: "DIAMOND"
        enchantments:
          - "DURABILITY:10"
        name: "<red>SERVER"
        lore:
          - ""
          - "<red>hey"
          - ""
        slot: 1
        amount: 1
        command: "queue join prison"
