license: ""

selector:
  item: "COMPASS"
  name: "<rainbow>Server Selector"
  enchantments:
    - "DURABILITY:10"
  lore:
    - ""
    - "<red>hey"
    - ""
  amount: 1
  slot: 1
hub:
  item: "CLOCK"
  name: "<rainbow>Hub Selector"
  enchantments:
    - "DURABILITY:10"
  lore:
    - ""
    - "<red>hey"
    - ""
  amount: 1
  slot: 2
pvp:
  item: "DIAMOND_SWORD"
  name: "<rainbow>PvP"
  enchantments:
    - "DURABILITY:10"
  lore:
    - ""
    - "<red>hey"
    - ""
  amount: 1
  slot: 3
enderbutt:
  item: "ENDER_PEARL"
  name: "<rainbow>EnderButt"
  enchantments:
    - "DURABILITY:10"
  lore:
    - ""
    - "<red>hey"
    - ""
  amount: 1
  slot: 4
inventory:
  selector:
    title: "<green>inventory"
    size: 54
    items:
      1:
        item: "DIAMOND"
        enchantments:
          - "DURABILITY:10"
        name: "<red>SERVER"
        lore:
          - ""
          - "<red>hey"
          - ""
        slot: 1
        amount: 1
        command: "queue join prison"
