name: zHub
version: "${pluginVersion}"
main: com.mizuledevelopment.zhub.zHub
api-version: "1.18"
website: "${pluginWebsite}"
author: "${pluginAuthor}"
description: "${pluginDescription}"
softdepend:
  - PlaceholderAPI
commands:
  zhub:
