name: zHub
version: "${pluginVersion}"
main: com.mizuledevelopment.zhub.zHub
api-version: "1.18"
website: "${pluginWebsite}"
database: false
author: "${pluginAuthor}"
description: "${pluginDescription}"
softdepend:
  - PlaceholderAPI